import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-white font-geist selection:bg-teal-500/30">
      <div className="max-w-3xl mx-auto px-6 py-24">
        <Link to="/" className="inline-flex items-center gap-2 text-white/40 hover:text-teal-400 transition-colors mb-12 group">
          <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          <span className="text-[10px] font-bold uppercase tracking-widest">Back to Home</span>
        </Link>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
        >
          <h1 className="text-4xl md:text-5xl font-light tracking-tight mb-4">Terms of Service</h1>
          <p className="text-white/30 text-xs mb-16 tracking-widest uppercase font-bold">Last updated: April 2026</p>

          <div className="space-y-12 text-white/60 leading-relaxed font-normal text-sm md:text-base">
            <section>
              <h2 className="text-white font-bold text-lg mb-4 tracking-tight">1. Internal Use Only</h2>
              <p>Tron is a beta tool intended strictly for internal use by authorized personnel. Redistribution or use outside of authorized teams is not permitted without explicit consent.</p>
            </section>

            <section>
              <h2 className="text-white font-bold text-lg mb-4 tracking-tight">2. No Warranty</h2>
              <p>This software is provided "as is" without warranty of any kind. Results generated by Tron are automated and may be inaccurate, incomplete, or misleading. You are solely responsible for verifying any output before acting on it.</p>
            </section>

            <section>
              <h2 className="text-white font-bold text-lg mb-4 tracking-tight">3. Limitation of Liability</h2>
              <p>The developer shall not be held liable for any damages, data loss, or issues arising from the use or misuse of this tool. Use at your own risk.</p>
            </section>

            <section>
              <h2 className="text-white font-bold text-lg mb-4 tracking-tight">4. Responsible Use</h2>
              <p>Do not use Tron on systems or URLs you do not own or have explicit permission to test. Unauthorized testing may be illegal in your jurisdiction.</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
